// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkpK_vdc2lxRY3y5rtDjopZImTedRsAS0',
    appId: '1:910223443706:web:f3c6084faad1c78bbfab43',
    messagingSenderId: '910223443706',
    projectId: 'sampahku-app-59393',
    authDomain: 'sampahku-app-59393.firebaseapp.com',
    storageBucket: 'sampahku-app-59393.firebasestorage.app',
    measurementId: 'G-50SJQ7BC8T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZVEgpeiJV59kWWQtxm5_Dmmd4-8LtuY4',
    appId: '1:910223443706:android:dc084a5898862004bfab43',
    messagingSenderId: '910223443706',
    projectId: 'sampahku-app-59393',
    storageBucket: 'sampahku-app-59393.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf0FbJCyfAK861VZiyzbUuief3u6FY1v8',
    appId: '1:910223443706:ios:2e9199f91b8b3c1dbfab43',
    messagingSenderId: '910223443706',
    projectId: 'sampahku-app-59393',
    storageBucket: 'sampahku-app-59393.firebasestorage.app',
    iosBundleId: 'com.example.sampahkuFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf0FbJCyfAK861VZiyzbUuief3u6FY1v8',
    appId: '1:910223443706:ios:2e9199f91b8b3c1dbfab43',
    messagingSenderId: '910223443706',
    projectId: 'sampahku-app-59393',
    storageBucket: 'sampahku-app-59393.firebasestorage.app',
    iosBundleId: 'com.example.sampahkuFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkpK_vdc2lxRY3y5rtDjopZImTedRsAS0',
    appId: '1:910223443706:web:75ce13e24193f5d0bfab43',
    messagingSenderId: '910223443706',
    projectId: 'sampahku-app-59393',
    authDomain: 'sampahku-app-59393.firebaseapp.com',
    storageBucket: 'sampahku-app-59393.firebasestorage.app',
    measurementId: 'G-VCFLKT5YRN',
  );

}